[package]
name = "libbbs-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.9.9"
sha3 = "0.9.1"
bls12_381 = { version = "0.8.0", features = ["experimental"] }
rand_core = { version = "0.6", features = ["getrandom"] }
